version: "3.4"

services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=dudlik
      - POSTGRES_PASSWORD=dudlik
      - POSTGRES_DB=dudlik
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/
    depends_on:
      - db
    env_file:
      - .env
    command: "/venv/bin/python manage.py runserver 0.0.0.0:8000"

  tailwind:
    build:
      context: .
      target: tailwind
    volumes:
      - ./:/app/
    tty: true

volumes:
  postgres_data:
